apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data: 
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen       80;
            listen  [::]:80;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }

            location ~ /api {
                proxy_pass  http://https://43.139.176.247:30011;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: orangear-frontend-svc
spec:
  selector:
    app: orangear-app
  type: NodePort
  ports:
  - port: 80
    nodePort: 30010
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orangear
spec:
  selector:
    matchLabels:
      app: orangear-app
  replicas: 2
  template:
    metadata:
      labels:
        app: orangear-app
    spec:
      containers:
      - name: orangear-container
        image: 43.139.176.247/fruit_buckets/orangear:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      imagePullSecrets:
        - name: harbor-secret
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oranget
spec:
  selector:
     matchLabels:
      app: oranget-app
  replicas: 2
  template:
    metadata:
      labels:
        app: oranget-app
    spec:
      containers:
      - name: oranget-container
        image: 43.139.176.247/fruit_buckets/oranget:latest
        imagePullPolicy: Always
      imagePullSecrets:
        - name: harbor-secret
---
apiVersion: v1
kind: Service
metadata:
  name: oranget-backend-svc
spec:
  selector:
    app: oranget-app
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30011
    targetPort: 8080

